/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.psj.common.avro.avdl;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SearchService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SearchService\",\"namespace\":\"com.psj.common.avro.avdl\",\"types\":[{\"type\":\"record\",\"name\":\"Entity\",\"fields\":[{\"name\":\"rowId\",\"type\":\"string\"},{\"name\":\"createdAt\",\"type\":\"string\"},{\"name\":\"text\",\"type\":\"string\"},{\"name\":\"attrs\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]},{\"type\":\"record\",\"name\":\"SearchResult\",\"fields\":[{\"name\":\"pageNo\",\"type\":\"int\"},{\"name\":\"pageSize\",\"type\":\"int\"},{\"name\":\"pageCount\",\"type\":\"int\"},{\"name\":\"totalItemCount\",\"type\":\"int\"},{\"name\":\"entities\",\"type\":{\"type\":\"array\",\"items\":\"Entity\"}}]}],\"messages\":{\"ping\":{\"request\":[],\"response\":\"string\"},\"persist\":{\"request\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"entity\",\"type\":\"Entity\"}],\"response\":\"int\"},\"persistAll\":{\"request\":[{\"name\":\"entities\",\"type\":{\"type\":\"array\",\"items\":\"Entity\"}}],\"response\":\"int\"},\"search\":{\"request\":[{\"name\":\"queryString\",\"type\":\"string\"},{\"name\":\"pageNo\",\"type\":\"int\",\"default\":1},{\"name\":\"pageSize\",\"type\":\"int\",\"default\":10}],\"response\":\"SearchResult\"}}}");
  /**
   */
  java.lang.CharSequence ping() throws org.apache.avro.AvroRemoteException;
  /**
   */
  int persist(java.lang.CharSequence id, com.psj.common.avro.avdl.Entity entity) throws org.apache.avro.AvroRemoteException;
  /**
   */
  int persistAll(java.util.List<com.psj.common.avro.avdl.Entity> entities) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.psj.common.avro.avdl.SearchResult search(java.lang.CharSequence queryString, int pageNo, int pageSize) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends SearchService {
    public static final org.apache.avro.Protocol PROTOCOL = com.psj.common.avro.avdl.SearchService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void persist(java.lang.CharSequence id, com.psj.common.avro.avdl.Entity entity, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void persistAll(java.util.List<com.psj.common.avro.avdl.Entity> entities, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void search(java.lang.CharSequence queryString, int pageNo, int pageSize, org.apache.avro.ipc.Callback<com.psj.common.avro.avdl.SearchResult> callback) throws java.io.IOException;
  }
}